<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessLogicWebAPILoGiud\02 - BusinessLogicWebAPILoGiud.csproj" />
    <ProjectReference Include="..\BusinessLogicWebAPILoGiud\02-BusinessLogicWebAPILoGiud.csproj" />
    <ProjectReference Include="..\BusinessLogicWebAPILoGiud\B_BusinessLogicWebAPILoGiud.csproj" />
    <ProjectReference Include="..\ModelsWebAPILoGiud\03 - ModelsWebAPILoGiud.csproj" />
    <ProjectReference Include="..\RepoImplementationWebAPILoGiud\05 - RepoImplWebAPILoGiud.csproj" />
    <ProjectReference Include="..\RepoImplementationWebAPILoGiud\E_RepoImplWebAPILoGiud.csproj" />
  </ItemGroup>

</Project>
